/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ConnectedSystemsRouteImport } from './routes/connected-systems'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as WorkforceBuilderRouteImport } from './routes/workforce-builder'
import { Route as AiEmployeesIndexRouteImport } from './routes/ai-employees/index'
import { Route as AiEmployeesSlugRouteImport } from './routes/ai-employees/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectedSystemsRoute = ConnectedSystemsRouteImport.update({
  id: '/connected-systems',
  path: '/connected-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkforceBuilderRoute = WorkforceBuilderRouteImport.update({
  id: '/workforce-builder',
  path: '/workforce-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AiEmployeesIndexRoute = AiEmployeesIndexRouteImport.update({
  id: '/ai-employees/',
  path: '/ai-employees/',
  getParentRoute: () => rootRouteImport,
} as any)
const AiEmployeesSlugRoute = AiEmployeesSlugRouteImport.update({
  id: '/ai-employees/$slug',
  path: '/ai-employees/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/case-studies': typeof CaseStudiesRoute
  '/checkout': typeof CheckoutRoute
  '/connected-systems': typeof ConnectedSystemsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/industries': typeof IndustriesRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/workforce-builder': typeof WorkforceBuilderRoute
  '/ai-employees/$slug': typeof AiEmployeesSlugRoute
  '/ai-employees/': typeof AiEmployeesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/case-studies': typeof CaseStudiesRoute
  '/checkout': typeof CheckoutRoute
  '/connected-systems': typeof ConnectedSystemsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/industries': typeof IndustriesRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/workforce-builder': typeof WorkforceBuilderRoute
  '/ai-employees/$slug': typeof AiEmployeesSlugRoute
  '/ai-employees': typeof AiEmployeesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/case-studies': typeof CaseStudiesRoute
  '/checkout': typeof CheckoutRoute
  '/connected-systems': typeof ConnectedSystemsRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/industries': typeof IndustriesRoute
  '/pricing': typeof PricingRoute
  '/resources': typeof ResourcesRoute
  '/workforce-builder': typeof WorkforceBuilderRoute
  '/ai-employees/$slug': typeof AiEmployeesSlugRoute
  '/ai-employees/': typeof AiEmployeesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/case-studies'
    | '/checkout'
    | '/connected-systems'
    | '/contact'
    | '/dashboard'
    | '/industries'
    | '/pricing'
    | '/resources'
    | '/workforce-builder'
    | '/ai-employees/$slug'
    | '/ai-employees/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/case-studies'
    | '/checkout'
    | '/connected-systems'
    | '/contact'
    | '/dashboard'
    | '/industries'
    | '/pricing'
    | '/resources'
    | '/workforce-builder'
    | '/ai-employees/$slug'
    | '/ai-employees'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/auth'
    | '/case-studies'
    | '/checkout'
    | '/connected-systems'
    | '/contact'
    | '/dashboard'
    | '/industries'
    | '/pricing'
    | '/resources'
    | '/workforce-builder'
    | '/ai-employees/$slug'
    | '/ai-employees/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  CaseStudiesRoute: typeof CaseStudiesRoute
  CheckoutRoute: typeof CheckoutRoute
  ConnectedSystemsRoute: typeof ConnectedSystemsRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  IndustriesRoute: typeof IndustriesRoute
  PricingRoute: typeof PricingRoute
  ResourcesRoute: typeof ResourcesRoute
  WorkforceBuilderRoute: typeof WorkforceBuilderRoute
  AiEmployeesSlugRoute: typeof AiEmployeesSlugRoute
  AiEmployeesIndexRoute: typeof AiEmployeesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connected-systems': {
      id: '/connected-systems'
      path: '/connected-systems'
      fullPath: '/connected-systems'
      preLoaderRoute: typeof ConnectedSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workforce-builder': {
      id: '/workforce-builder'
      path: '/workforce-builder'
      fullPath: '/workforce-builder'
      preLoaderRoute: typeof WorkforceBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-employees/': {
      id: '/ai-employees/'
      path: '/ai-employees'
      fullPath: '/ai-employees/'
      preLoaderRoute: typeof AiEmployeesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-employees/$slug': {
      id: '/ai-employees/$slug'
      path: '/ai-employees/$slug'
      fullPath: '/ai-employees/$slug'
      preLoaderRoute: typeof AiEmployeesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  CaseStudiesRoute: CaseStudiesRoute,
  CheckoutRoute: CheckoutRoute,
  ConnectedSystemsRoute: ConnectedSystemsRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  IndustriesRoute: IndustriesRoute,
  PricingRoute: PricingRoute,
  ResourcesRoute: ResourcesRoute,
  WorkforceBuilderRoute: WorkforceBuilderRoute,
  AiEmployeesSlugRoute: AiEmployeesSlugRoute,
  AiEmployeesIndexRoute: AiEmployeesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
